import Currency from '../models/Currency.js';

const currencies = [
    { title: 'US Dollar', code: 'USD', rate: 1, isBase: true },

    // Tier 2: Major global currencies (high trading volume)
    { title: 'Euro', code: 'EUR' },
    { title: 'Japanese Yen', code: 'JPY' },
    { title: 'British Pound Sterling', code: 'GBP' },
    { title: 'Australian Dollar', code: 'AUD' },
    { title: 'Canadian Dollar', code: 'CAD' },
    { title: 'Swiss Franc', code: 'CHF' },
    { title: 'Chinese Yuan', code: 'CNY' },
  
    // Tier 3: Original currencies (sorted A-Z excluding USD/majors)
    { title: 'Afghan Afghani', code: 'AFN' },
    { title: 'Albanian Lek', code: 'ALL' },
    { title: 'Algerian Dinar', code: 'DZD' },
    { title: 'Angolan Kwanza', code: 'AOA' },
    { title: 'Argentine Peso', code: 'ARS' },
    { title: 'Armenian Dram', code: 'AMD' },
    { title: 'Aruban Florin', code: 'AWG' },
    { title: 'Azerbaijani Manat', code: 'AZN' },
    { title: 'Bahamian Dollar', code: 'BSD' },
    { title: 'Bahraini Dinar', code: 'BHD' },
    { title: 'Bangladeshi Taka', code: 'BDT' },
    { title: 'Barbadian Dollar', code: 'BBD' },
    { title: 'Belarusian Ruble', code: 'BYN' },
    { title: 'Belize Dollar', code: 'BZD' },
    { title: 'Bermudian Dollar', code: 'BMD' },
    { title: 'Bhutanese Ngultrum', code: 'BTN' },
    { title: 'Bolivian Boliviano', code: 'BOB' },
    { title: 'Bosnia-Herzegovina Convertible Mark', code: 'BAM' },
    { title: 'Botswanan Pula', code: 'BWP' },
    { title: 'Brazilian Real', code: 'BRL' },
    { title: 'Brunei Dollar', code: 'BND' },
    { title: 'Bulgarian Lev', code: 'BGN' },
    { title: 'Burundian Franc', code: 'BIF' },
    { title: 'Cape Verdean Escudo', code: 'CVE' },
    { title: 'Cambodian Riel', code: 'KHR' },
    { title: 'Cayman Islands Dollar', code: 'KYD' },
    { title: 'CFA Franc BCEAO', code: 'XOF' },
    { title: 'CFA Franc BEAC', code: 'XAF' },
    { title: 'CFP Franc', code: 'XPF' },
    { title: 'Chilean Peso', code: 'CLP' },
    { title: 'Colombian Peso', code: 'COP' },
    { title: 'Comorian Franc', code: 'KMF' },
    { title: 'Congolese Franc', code: 'CDF' },
    { title: 'Costa Rican Colón', code: 'CRC' },
    { title: 'Croatian Kuna', code: 'HRK' },
    { title: 'Cuban Peso', code: 'CUP' },
    { title: 'Czech Republic Koruna', code: 'CZK' },
    { title: 'Djiboutian Franc', code: 'DJF' },
    { title: 'Dominican Peso', code: 'DOP' },
    { title: 'East Caribbean Dollar', code: 'XCD' },
    { title: 'Egyptian Pound', code: 'EGP' },
    { title: 'Eritrean Nakfa', code: 'ERN' },
    { title: 'Eswatini Lilangeni', code: 'SZL' },
    { title: 'Ethiopian Birr', code: 'ETB' },
    { title: 'Falkland Islands Pound', code: 'FKP' },
    { title: 'Fijian Dollar', code: 'FJD' },
    { title: 'Gambian Dalasi', code: 'GMD' },
    { title: 'Georgian Lari', code: 'GEL' },
    { title: 'Ghanaian Cedi', code: 'GHS' },
    { title: 'Gibraltar Pound', code: 'GIP' },
    { title: 'Guatemalan Quetzal', code: 'GTQ' },
    { title: 'Guinean Franc', code: 'GNF' },
    { title: 'Guyanaese Dollar', code: 'GYD' },
    { title: 'Haitian Gourde', code: 'HTG' },
    { title: 'Honduran Lempira', code: 'HNL' },
    { title: 'Hungarian Forint', code: 'HUF' },
    { title: 'Icelandic Króna', code: 'ISK' },
    { title: 'Indian Rupee', code: 'INR' },
    { title: 'Indonesian Rupiah', code: 'IDR' },
    { title: 'Iranian Rial', code: 'IRR' },
    { title: 'Iraqi Dinar', code: 'IQD' },
    { title: 'Israeli New Sheqel', code: 'ILS' },
    { title: 'Jamaican Dollar', code: 'JMD' },
    { title: 'Jordanian Dinar', code: 'JOD' },
    { title: 'Kazakhstani Tenge', code: 'KZT' },
    { title: 'Kenyan Shilling', code: 'KES' },
    { title: 'Kuwaiti Dinar', code: 'KWD' },
    { title: 'Kyrgystani Som', code: 'KGS' },
    { title: 'Laotian Kip', code: 'LAK' },
    { title: 'Lebanese Pound', code: 'LBP' },
    { title: 'Lesotho Loti', code: 'LSL' },
    { title: 'Liberian Dollar', code: 'LRD' },
    { title: 'Libyan Dinar', code: 'LYD' },
    { title: 'Macanese Pataca', code: 'MOP' },
    { title: 'Malagasy Ariary', code: 'MGA' },
    { title: 'Malawian Kwacha', code: 'MWK' },
    { title: 'Malaysian Ringgit', code: 'MYR' },
    { title: 'Maldivian Rufiyaa', code: 'MVR' },
    { title: 'Mauritanian Ouguiya', code: 'MRU' },
    { title: 'Mauritian Rupee', code: 'MUR' },
    { title: 'Mexican Peso', code: 'MXN' },
    { title: 'Moldovan Leu', code: 'MDL' },
    { title: 'Mongolian Tugrik', code: 'MNT' },
    { title: 'Moroccan Dirham', code: 'MAD' },
    { title: 'Mozambican Metical', code: 'MZN' },
    { title: 'Myanmar Kyat', code: 'MMK' },
    { title: 'Namibian Dollar', code: 'NAD' },
    { title: 'Nepalese Rupee', code: 'NPR' },
    { title: 'Netherlands Antillean Guilder', code: 'ANG' },
    { title: 'New Taiwan Dollar', code: 'TWD' },
    { title: 'New Zealand Dollar', code: 'NZD' },
    { title: 'Nicaraguan Córdoba', code: 'NIO' },
    { title: 'Nigerian Naira', code: 'NGN' },
    { title: 'North Korean Won', code: 'KPW' },
    { title: 'Omani Rial', code: 'OMR' },
    { title: 'Pakistani Rupee', code: 'PKR' },
    { title: 'Panamanian Balboa', code: 'PAB' },
    { title: 'Papua New Guinean Kina', code: 'PGK' },
    { title: 'Paraguayan Guarani', code: 'PYG' },
    { title: 'Peruvian Nuevo Sol', code: 'PEN' },
    { title: 'Philippine Peso', code: 'PHP' },
    { title: 'Polish Zloty', code: 'PLN' },
    { title: 'Qatari Rial', code: 'QAR' },
    { title: 'Romanian Leu', code: 'RON' },
    { title: 'Russian Ruble', code: 'RUB' },
    { title: 'Rwandan Franc', code: 'RWF' },
    { title: 'Saint Helena Pound', code: 'SHP' },
    { title: 'Samoan Tala', code: 'WST' },
    { title: 'São Tomé and Príncipe Dobra', code: 'STN' },
    { title: 'Saudi Riyal', code: 'SAR' },
    { title: 'Serbian Dinar', code: 'RSD' },
    { title: 'Seychellois Rupee', code: 'SCR' },
    { title: 'Sierra Leonean Leone', code: 'SLE' },
    { title: 'Singapore Dollar', code: 'SGD' },
    { title: 'Solomon Islands Dollar', code: 'SBD' },
    { title: 'Somali Shilling', code: 'SOS' },
    { title: 'South African Rand', code: 'ZAR' },
    { title: 'South Korean Won', code: 'KRW' },
    { title: 'South Sudanese Pound', code: 'SSP' },
    { title: 'Sri Lankan Rupee', code: 'LKR' },
    { title: 'Sudanese Pound', code: 'SDG' },
    { title: 'Surinamese Dollar', code: 'SRD' },
    { title: 'Swedish Krona', code: 'SEK' },
    { title: 'Syrian Pound', code: 'SYP' },
    { title: 'Tajikistani Somoni', code: 'TJS' },
    { title: 'Tanzanian Shilling', code: 'TZS' },
    { title: 'Thai Baht', code: 'THB' },
    { title: 'Tongan Paʻanga', code: 'TOP' },
    { title: 'Trinidad and Tobago Dollar', code: 'TTD' },
    { title: 'Tunisian Dinar', code: 'TND' },
    { title: 'Turkish Lira', code: 'TRY' },
    { title: 'Turkmenistani Manat', code: 'TMT' },
    { title: 'Ugandan Shilling', code: 'UGX' },
    { title: 'Ukrainian Hryvnia', code: 'UAH' },
    { title: 'Uruguayan Peso', code: 'UYU' },
    { title: 'Uzbekistan Som', code: 'UZS' },
    { title: 'Vanuatu Vatu', code: 'VUV' },
    { title: 'Venezuelan Bolívar', code: 'VES' },
    { title: 'Vietnamese Dong', code: 'VND' },
    { title: 'Yemeni Rial', code: 'YER' },
    { title: 'Zambian Kwacha', code: 'ZMW' },
    
    // Tier 4: Added popular currencies (to reach 100)
    { title: 'Hong Kong Dollar', code: 'HKD' },
    { title: 'Norwegian Krone', code: 'NOK' },
    { title: 'Danish Krone', code: 'DKK' },
    { title: 'Hungarian Forint', code: 'HUF' },
    { title: 'Czech Koruna', code: 'CZK' },
    { title: 'Chilean Peso', code: 'CLP' },
    { title: 'Philippine Peso', code: 'PHP' },
    { title: 'Romanian Leu', code: 'RON' },
    { title: 'Peruvian Sol', code: 'PEN' },
    { title: 'Bahraini Dinar', code: 'BHD' },
    { title: 'Kuwaiti Dinar', code: 'KWD' },
    { title: 'Uruguayan Peso', code: 'UYU' },
    { title: 'Costa Rican Colón', code: 'CRC' },
    { title: 'Qatari Rial', code: 'QAR' },
    { title: 'Guatemalan Quetzal', code: 'GTQ' }
];

export const initializeCurrencies = async () => {
  try {
    const count = await Currency.countDocuments();
    if (count === 0) {
      await Currency.insertMany(currencies);
      console.log('Currencies database initialized');
    }
  } catch (error) {
    console.error('Currency initialization error:', error);
  }
};